### ISSUE TITLE
Error reported for training classifier using meta-Dataset on multi-GPUs

### ISSUE THREAD

**Issue by tao0420** [yinboc/few-shot-meta-baseline#30]
Hi there,

Thanks for the great work! 

I followed the README.md instructions on training classifier/multi-classifier on meta-Dataset. However when using multi-GPUs, the error reported as the following:

Traceback (most recent call last):
  File "train_classifier.py", line 195, in <module>
    main(config)
  File "train_classifier.py", line 107, in main
    loss = F.cross_entropy(logits, label)
  File "/home/anaconda3/envs/fewshot_torch17/lib/python3.7/site-packages/torch/nn/functional.py", line 2468, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/anaconda3/envs/fewshot_torch17/lib/python3.7/site-packages/torch/nn/functional.py", line 2264, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: Assertion `THCTensor_(checkGPU)(state, 4, input, target, output, total_weight)' failed. Some of weight/gradient/input tensors are located on different GPUs. Please move them to a single one. at /opt/conda/conda-bld/pytorch_1603729006826/work/aten/src/THCUNN/generic/ClassNLLCriterion.cu:28

No changes are made on the original code. I am wondering if you have any clue on this?

**Comment by tao0420** [comment]
Never mind. Using cpu version of the tensorflow solves this.
